# Liberty Gaming - Halo CE Website
# Developer: Jericho Crosby / Chalwk
# Copyright (c) 2026 Liberty Gaming - Halo CE. All rights reserved.
# This file is part of the proprietary Liberty Gaming website.
# Use, copying, or distribution without permission is strictly prohibited.

title: Liberty Gaming - Halo CE
description: Official website for Liberty Gaming Halo CE community.
baseurl: ""
url: "https://liberty-ce.net"